name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Nuclei
      uses: projectdiscovery/nuclei-action@main
      with:
        target: ‘http://app.selluseller.com/’
        github-report: true
        github-token: ${{ secrets.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 }}
